/**
 * Contaxy API
 * Functionality to create and manage projects, services, jobs, and files.
 *
 * The version of the OpenAPI document: 0.0.0.dev1+main
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class OAuth2TokenGrantTypes.
* @enum {}
* @readonly
*/
export default class OAuth2TokenGrantTypes {
    
        /**
         * value: "password"
         * @const
         */
        "password" = "password";

    
        /**
         * value: "refresh_token"
         * @const
         */
        "refresh_token" = "refresh_token";

    
        /**
         * value: "client_credentials"
         * @const
         */
        "client_credentials" = "client_credentials";

    
        /**
         * value: "authorization_code"
         * @const
         */
        "authorization_code" = "authorization_code";

    

    /**
    * Returns a <code>OAuth2TokenGrantTypes</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/OAuth2TokenGrantTypes} The enum <code>OAuth2TokenGrantTypes</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

