/**
 * Contaxy API
 * Functionality to create and manage projects, services, jobs, and files.
 *
 * The version of the OpenAPI document: 0.0.0.dev1+main
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Quota model module.
 * @module model/Quota
 * @version 0.0.0.dev1+main
 */
class Quota {
    /**
     * Constructs a new <code>Quota</code>.
     * @alias module:model/Quota
     */
    constructor() { 
        
        Quota.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Quota</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Quota} obj Optional instance to populate.
     * @return {module:model/Quota} The populated <code>Quota</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Quota();

            if (data.hasOwnProperty('max_cpus')) {
                obj['max_cpus'] = ApiClient.convertToType(data['max_cpus'], 'Number');
            }
            if (data.hasOwnProperty('max_memory')) {
                obj['max_memory'] = ApiClient.convertToType(data['max_memory'], 'Number');
            }
            if (data.hasOwnProperty('max_gpus')) {
                obj['max_gpus'] = ApiClient.convertToType(data['max_gpus'], 'Number');
            }
            if (data.hasOwnProperty('max_deployment_storage')) {
                obj['max_deployment_storage'] = ApiClient.convertToType(data['max_deployment_storage'], 'Number');
            }
            if (data.hasOwnProperty('max_file_storage')) {
                obj['max_file_storage'] = ApiClient.convertToType(data['max_file_storage'], 'Number');
            }
            if (data.hasOwnProperty('max_files')) {
                obj['max_files'] = ApiClient.convertToType(data['max_files'], 'Number');
            }
            if (data.hasOwnProperty('max_deployments')) {
                obj['max_deployments'] = ApiClient.convertToType(data['max_deployments'], 'Number');
            }
            if (data.hasOwnProperty('max_collections')) {
                obj['max_collections'] = ApiClient.convertToType(data['max_collections'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Maximum number of CPU cores.
 * @member {Number} max_cpus
 */
Quota.prototype['max_cpus'] = undefined;

/**
 * Maximum amount of memory in Megabyte.
 * @member {Number} max_memory
 */
Quota.prototype['max_memory'] = undefined;

/**
 * Maximum number of GPUs.
 * @member {Number} max_gpus
 */
Quota.prototype['max_gpus'] = undefined;

/**
 * Maximum storage usage in Megabyte for all deployments.
 * @member {Number} max_deployment_storage
 */
Quota.prototype['max_deployment_storage'] = undefined;

/**
 * Maximum storage usage in Megabyte for all files.
 * @member {Number} max_file_storage
 */
Quota.prototype['max_file_storage'] = undefined;

/**
 * Maximum number of files on file storage.
 * @member {Number} max_files
 */
Quota.prototype['max_files'] = undefined;

/**
 * Maximum number of deployments. This includes services, jobs, and extensions.
 * @member {Number} max_deployments
 */
Quota.prototype['max_deployments'] = undefined;

/**
 * Maximum number of JSON document collections.
 * @member {Number} max_collections
 */
Quota.prototype['max_collections'] = undefined;






export default Quota;

