/**
 * Contaxy API
 * Functionality to create and manage projects, services, jobs, and files.
 *
 * The version of the OpenAPI document: 0.0.0.dev1+main
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class TokenPurpose.
* @enum {}
* @readonly
*/
export default class TokenPurpose {
    
        /**
         * value: "user-generated"
         * @const
         */
        "user-generated" = "user-generated";

    
        /**
         * value: "refresh-token"
         * @const
         */
        "refresh-token" = "refresh-token";

    
        /**
         * value: "deployment-token"
         * @const
         */
        "deployment-token" = "deployment-token";

    

    /**
    * Returns a <code>TokenPurpose</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/TokenPurpose} The enum <code>TokenPurpose</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

